name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    env:
      APPROVALS: "1"
      ADD_LABELS: "approved"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master      
